export const TimelineElements = [
    {
        id: 1,
        title: "Graduação em Ciências Biológicas",
        location: "Universidade Estadual do Paraná",
        date: "Dec 2015 - Dec 2018",
        description: "Adquiri habilidades e experiência com desenvolvimento de pesquisas científicas, redação de relatórios e ministração de aulas, além de ter o meu primeiro contato com programação.",
        buttonText: "Projeto de Bioinformática",
        icon: "graduation",   
    },
    {
        id: 2,
        title: "Mestrado em Ciência e Tecnologia Ambiental",
        location: "Universidade Tecnológica Federal do Paraná",
        date: "Aug 2019 - Feb 2023",
        description: "Desenvolvi minha pesquisa e trabalhei no laboratório de Ecotoxicologia.",
        buttonText: "Dissertação",
        icon: "work",   
    },
    {
        id: 3,
        title: "Professora",
        location: "Instituições públicas, privadas e ONGs",
        date: "Aug 2018 - Feb 2022",
        description: "Ministrei aulas para alunos de diferentes faixas etárias, desde o ensino fundamental até o técnico/profissionalizante.",
        buttonText: "",
        icon: "work",   
    },
    {
        id: 4,
        title: "Intercâmbio de língua inglesa",
        location: "Irlanda",
        date: "Dec 2022 - Dec 2023",
        description: "Estudei inglês e trabalhei com atendimento ao público.",
        buttonText: "",
        icon: "graduation",   
    },
    {
        id: 5,
        title: "Front-end",
        location: "Udemy - Hora de Codar",
        date: "Nov 2023 - Mar 2024",
        description: "Curso contempla HTML, CSS, JS, React, Typescript.",
        buttonText: "",
        icon: "graduation",   
    },
    {
        id: 6,
        title: "Full Stack Java and UI Design",
        location: "EBAC - Escola Britânica de Artes Criativas e Tecnologias",
        date: "Dec 2023 - present",
        description: "Curso abrange lógica de programação, versionamento de projetos, desenvolvimento web e UI design.",
        buttonText: "",
        icon: "graduation",   
    },
    {
        id: 7,
        title: "Freelance Developer",
        location: "Curitiba, Paraná",
        date: "Mar 2024 - present",
        description: "Estou desenvolvendo landing pages para pequenas empresas.",
        icon: "work",   
    },
]