export const TimelineElements = [
    {
        id: 1,
        title: "Graduação - Tecnologia em Análise e Desenvolvimento de Sistemas",
        location: " Instituto Federal do Paraná - IFPR ",
        date: "Fev 2025 - Dez 2027",
        description: "Cursei disciplinas como Banco de Dados, Lógica de Programação, Programação em C, Desenvolvimento Web, Engenharia de Software, Arquitetura de Computadores e Matemática Computacional, entre outras.",
        buttonText: "",
        icon: "graduation",   
    },
    {
        id: 2,
        title: "CoralTech",
        location: "Curitiba, Paraná",
        date: "Fev 2024 - Fev 2025",
        description: "Desenvolvi sites personalizados, do design no Figma à implementação final.",
        buttonText: "",
        icon: "work",   
    },
    {
        id: 3,
        title: "Front-end and UI Design",
        location: "EBAC - Escola Britânica de Artes Criativas e Tecnologias",
        date: "Fev 2024 - nov 2025",
        description: "Curso abrange lógica de programação, versionamento de projetos, desenvolvimento web e UI design.",
        buttonText: "",
        icon: "graduation",   
    },
    {
        id: 4,
        title: "Front-end",
        location: "Udemy - Hora de Codar",
        date: "Nov 2023 - Mar 2024",
        description: "Curso contempla HTML, CSS, JS, React, Typescript.",
        buttonText: "",
        icon: "graduation",   
    },
    {
        id: 5,
        title: "Intercâmbio de Língua Inglesa ",
        location: " ISI - Ireland ",
        date: "Nov 2022 - Dez 2023",
        description: "Durante meu intercâmbio na língua inglesa, tive a oportunidade de trabalhar e estudar na Irlanda. Essa experiência foi extremamente valiosa, pois me permitiu praticar e melhorar minhas habilidades de fala e audição com falantes nativos.",
        buttonText: "",
        icon: "work",   
    },
    {
        id: 7,
        title: "Graduação em Ciências Biológicas",
        location: "Universidade Estadual do Paraná",
        date: "Jan 2015 - Dez 2018",
        description: "Desenvolvi minha pesquisa e trabalhei no laboratório de Ecologia.",
        buttonText: "",
        icon: "graduation",   
    },
]